# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell

[package]
name = "oikosbot-pareto"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
oikosbot-metrics = { path = "../oikosbot-metrics" }
serde.workspace = true
