// Generated by ReScript, PLEASE EDIT WITH CARE


var Env = {};

var Http = {};

var $$Crypto = {};

var $$TextEncoder = {};

var $$TextDecoder = {};

export {
  Env ,
  Http ,
  $$Crypto ,
  $$TextEncoder ,
  $$TextDecoder ,
}
/* No side effect */
