// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Belt_Result from "@rescript/runtime/lib/es6/Belt_Result.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function decodeField(obj, key) {
  let v = Js_dict.get(obj, key);
  if (v !== undefined) {
    return {
      TAG: "Ok",
      _0: v
    };
  } else {
    return {
      TAG: "Error",
      _0: `missing field: ` + key
    };
  }
}

function decodeOptField(obj, key) {
  let v = Js_dict.get(obj, key);
  if (v === undefined) {
    return;
  }
  let match = Js_json.classify(v);
  if (typeof match !== "object" && match === "JSONNull") {
    return;
  } else {
    return v;
  }
}

function asObject(path, json) {
  let obj = Js_json.decodeObject(json);
  if (obj !== undefined) {
    return {
      TAG: "Ok",
      _0: obj
    };
  } else {
    return {
      TAG: "Error",
      _0: path + `: expected object`
    };
  }
}

function asString(path, json) {
  let s = Js_json.decodeString(json);
  if (s !== undefined) {
    return {
      TAG: "Ok",
      _0: s
    };
  } else {
    return {
      TAG: "Error",
      _0: path + `: expected string`
    };
  }
}

function asFloat(path, json) {
  let n = Js_json.decodeNumber(json);
  if (n !== undefined) {
    return {
      TAG: "Ok",
      _0: n
    };
  } else {
    return {
      TAG: "Error",
      _0: path + `: expected number`
    };
  }
}

function asInt(path, json) {
  return Belt_Result.map(asFloat(path, json), prim => prim | 0);
}

function asBool(path, json) {
  let b = Js_json.decodeBoolean(json);
  if (b !== undefined) {
    return {
      TAG: "Ok",
      _0: b
    };
  } else {
    return {
      TAG: "Error",
      _0: path + `: expected boolean`
    };
  }
}

function asArray(path, json) {
  let a = Js_json.decodeArray(json);
  if (a !== undefined) {
    return {
      TAG: "Ok",
      _0: a
    };
  } else {
    return {
      TAG: "Error",
      _0: path + `: expected array`
    };
  }
}

function mapArray(arr, decoder, path) {
  let out = [];
  let err = {
    contents: undefined
  };
  Belt_Array.forEachWithIndex(arr, (i, item) => {
    if (err.contents !== undefined) {
      return;
    }
    let v = decoder(path + `[` + String(i) + `]`, item);
    if (v.TAG !== "Ok") {
      err.contents = v._0;
      return;
    }
    out.push(v._0);
  });
  let e = err.contents;
  if (e !== undefined) {
    return {
      TAG: "Error",
      _0: e
    };
  } else {
    return {
      TAG: "Ok",
      _0: out
    };
  }
}

function decodeFloatField(obj, path, key) {
  return Belt_Result.flatMap(decodeField(obj, key), v => asFloat(path + `.` + key, v));
}

function decodeStringField(obj, path, key) {
  return Belt_Result.flatMap(decodeField(obj, key), v => asString(path + `.` + key, v));
}

function decodeBoolField(obj, path, key) {
  return Belt_Result.flatMap(decodeField(obj, key), v => asBool(path + `.` + key, v));
}

function decodeEcoMetrics(path, json) {
  return Belt_Result.flatMap(asObject(path, json), obj => {
    let match = decodeFloatField(obj, path, "carbonScore");
    let match$1 = decodeFloatField(obj, path, "energyScore");
    let match$2 = decodeFloatField(obj, path, "resourceScore");
    let match$3 = decodeFloatField(obj, path, "score");
    if (match.TAG === "Ok") {
      if (match$1.TAG === "Ok") {
        if (match$2.TAG === "Ok") {
          if (match$3.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                carbonScore: match._0,
                energyScore: match$1._0,
                resourceScore: match$2._0,
                score: match$3._0
              }
            };
          } else {
            return {
              TAG: "Error",
              _0: match$3._0
            };
          }
        } else {
          return {
            TAG: "Error",
            _0: match$2._0
          };
        }
      } else {
        return {
          TAG: "Error",
          _0: match$1._0
        };
      }
    } else {
      return {
        TAG: "Error",
        _0: match._0
      };
    }
  });
}

function decodeImprovements(path, json) {
  return Belt_Result.flatMap(asArray(path, json), arr => mapArray(arr, asString, path));
}

function decodeParetoStatus(path, json) {
  return Belt_Result.flatMap(asObject(path, json), obj => {
    let isOptimal = decodeBoolField(obj, path, "isOptimal");
    let distance = decodeFloatField(obj, path, "distance");
    let v = decodeOptField(obj, "improvements");
    let improvements = v !== undefined ? Belt_Result.map(decodeImprovements(path + `.improvements`, v), arr => arr) : ({
        TAG: "Ok",
        _0: undefined
      });
    if (isOptimal.TAG === "Ok") {
      if (distance.TAG === "Ok") {
        if (improvements.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              isOptimal: isOptimal._0,
              distance: distance._0,
              improvements: improvements._0
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: improvements._0
          };
        }
      } else {
        return {
          TAG: "Error",
          _0: distance._0
        };
      }
    } else {
      return {
        TAG: "Error",
        _0: isOptimal._0
      };
    }
  });
}

function decodeEconMetrics(path, json) {
  return Belt_Result.flatMap(asObject(path, json), obj => {
    let paretoDistance = decodeFloatField(obj, path, "paretoDistance");
    let allocationScore = decodeFloatField(obj, path, "allocationScore");
    let debtScore = decodeFloatField(obj, path, "debtScore");
    let score = decodeFloatField(obj, path, "score");
    let v = decodeOptField(obj, "paretoStatus");
    let paretoStatus = v !== undefined ? Belt_Result.map(decodeParetoStatus(path + `.paretoStatus`, v), ps => ps) : ({
        TAG: "Ok",
        _0: undefined
      });
    if (paretoDistance.TAG === "Ok") {
      if (allocationScore.TAG === "Ok") {
        if (debtScore.TAG === "Ok") {
          if (score.TAG === "Ok") {
            if (paretoStatus.TAG === "Ok") {
              return {
                TAG: "Ok",
                _0: {
                  paretoDistance: paretoDistance._0,
                  allocationScore: allocationScore._0,
                  debtScore: debtScore._0,
                  score: score._0,
                  paretoStatus: paretoStatus._0
                }
              };
            } else {
              return {
                TAG: "Error",
                _0: paretoStatus._0
              };
            }
          } else {
            return {
              TAG: "Error",
              _0: score._0
            };
          }
        } else {
          return {
            TAG: "Error",
            _0: debtScore._0
          };
        }
      } else {
        return {
          TAG: "Error",
          _0: allocationScore._0
        };
      }
    } else {
      return {
        TAG: "Error",
        _0: paretoDistance._0
      };
    }
  });
}

function decodeQualityMetrics(path, json) {
  return Belt_Result.flatMap(asObject(path, json), obj => {
    let match = decodeFloatField(obj, path, "complexityScore");
    let match$1 = decodeFloatField(obj, path, "couplingScore");
    let match$2 = decodeFloatField(obj, path, "coverageScore");
    let match$3 = decodeFloatField(obj, path, "score");
    if (match.TAG === "Ok") {
      if (match$1.TAG === "Ok") {
        if (match$2.TAG === "Ok") {
          if (match$3.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                complexityScore: match._0,
                couplingScore: match$1._0,
                coverageScore: match$2._0,
                score: match$3._0
              }
            };
          } else {
            return {
              TAG: "Error",
              _0: match$3._0
            };
          }
        } else {
          return {
            TAG: "Error",
            _0: match$2._0
          };
        }
      } else {
        return {
          TAG: "Error",
          _0: match$1._0
        };
      }
    } else {
      return {
        TAG: "Error",
        _0: match._0
      };
    }
  });
}

function decodeHealthIndex(path, json) {
  return Belt_Result.flatMap(asObject(path, json), obj => {
    let match = decodeFloatField(obj, path, "eco");
    let match$1 = decodeFloatField(obj, path, "econ");
    let match$2 = decodeFloatField(obj, path, "quality");
    let match$3 = decodeFloatField(obj, path, "total");
    let match$4 = decodeStringField(obj, path, "grade");
    if (match.TAG === "Ok") {
      if (match$1.TAG === "Ok") {
        if (match$2.TAG === "Ok") {
          if (match$3.TAG === "Ok") {
            if (match$4.TAG === "Ok") {
              return {
                TAG: "Ok",
                _0: {
                  eco: match._0,
                  econ: match$1._0,
                  quality: match$2._0,
                  total: match$3._0,
                  grade: match$4._0
                }
              };
            } else {
              return {
                TAG: "Error",
                _0: match$4._0
              };
            }
          } else {
            return {
              TAG: "Error",
              _0: match$3._0
            };
          }
        } else {
          return {
            TAG: "Error",
            _0: match$2._0
          };
        }
      } else {
        return {
          TAG: "Error",
          _0: match$1._0
        };
      }
    } else {
      return {
        TAG: "Error",
        _0: match._0
      };
    }
  });
}

function decodeSeverity(path, json) {
  return Belt_Result.flatMap(asString(path, json), s => {
    let other = s.toLowerCase();
    switch (other) {
      case "blocking" :
        return {
          TAG: "Ok",
          _0: "Blocking"
        };
      case "high" :
        return {
          TAG: "Ok",
          _0: "High"
        };
      case "info" :
        return {
          TAG: "Ok",
          _0: "Info"
        };
      case "low" :
        return {
          TAG: "Ok",
          _0: "Low"
        };
      case "medium" :
        return {
          TAG: "Ok",
          _0: "Medium"
        };
      default:
        return {
          TAG: "Error",
          _0: path + `: unknown severity '` + other + `'`
        };
    }
  });
}

function decodePriority(path, json) {
  return Belt_Result.flatMap(asString(path, json), s => {
    let other = s.toLowerCase();
    switch (other) {
      case "high" :
        return {
          TAG: "Ok",
          _0: "PriorityHigh"
        };
      case "low" :
        return {
          TAG: "Ok",
          _0: "PriorityLow"
        };
      case "medium" :
        return {
          TAG: "Ok",
          _0: "PriorityMedium"
        };
      default:
        return {
          TAG: "Error",
          _0: path + `: unknown priority '` + other + `'`
        };
    }
  });
}

function decodeLocation(path, json) {
  return Belt_Result.flatMap(asObject(path, json), obj => {
    let file = decodeStringField(obj, path, "file");
    let line = Belt_Result.flatMap(decodeField(obj, "line"), v => asInt(path + `.line`, v));
    let v = decodeOptField(obj, "column");
    let column = v !== undefined ? Belt_Result.map(asInt(path + `.column`, v), i => i) : ({
        TAG: "Ok",
        _0: undefined
      });
    if (file.TAG === "Ok") {
      if (line.TAG === "Ok") {
        if (column.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              file: file._0,
              line: line._0,
              column: column._0
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: column._0
          };
        }
      } else {
        return {
          TAG: "Error",
          _0: line._0
        };
      }
    } else {
      return {
        TAG: "Error",
        _0: file._0
      };
    }
  });
}

function decodeViolation(path, json) {
  return Belt_Result.flatMap(asObject(path, json), obj => {
    let entityId = decodeStringField(obj, path, "entityId");
    let policy = decodeStringField(obj, path, "policy");
    let severity = Belt_Result.flatMap(decodeField(obj, "severity"), v => decodeSeverity(path + `.severity`, v));
    let message = decodeStringField(obj, path, "message");
    let v = decodeOptField(obj, "location");
    let location = v !== undefined ? Belt_Result.map(decodeLocation(path + `.location`, v), l => l) : ({
        TAG: "Ok",
        _0: undefined
      });
    let v$1 = decodeOptField(obj, "suggestions");
    let suggestions = v$1 !== undefined ? Belt_Result.flatMap(asArray(path + `.suggestions`, v$1), arr => mapArray(arr, asString, path + `.suggestions`)) : ({
        TAG: "Ok",
        _0: []
      });
    if (entityId.TAG === "Ok") {
      if (policy.TAG === "Ok") {
        if (severity.TAG === "Ok") {
          if (message.TAG === "Ok") {
            if (location.TAG === "Ok") {
              if (suggestions.TAG === "Ok") {
                return {
                  TAG: "Ok",
                  _0: {
                    entityId: entityId._0,
                    policy: policy._0,
                    severity: severity._0,
                    message: message._0,
                    location: location._0,
                    suggestions: suggestions._0
                  }
                };
              } else {
                return {
                  TAG: "Error",
                  _0: suggestions._0
                };
              }
            } else {
              return {
                TAG: "Error",
                _0: location._0
              };
            }
          } else {
            return {
              TAG: "Error",
              _0: message._0
            };
          }
        } else {
          return {
            TAG: "Error",
            _0: severity._0
          };
        }
      } else {
        return {
          TAG: "Error",
          _0: policy._0
        };
      }
    } else {
      return {
        TAG: "Error",
        _0: entityId._0
      };
    }
  });
}

function decodeExpectedImprovement(path, json) {
  return Belt_Result.flatMap(asObject(path, json), obj => {
    let out = {};
    let err = {
      contents: undefined
    };
    Belt_Array.forEach(Object.keys(obj), k => {
      if (err.contents !== undefined) {
        return;
      }
      let v = Js_dict.get(obj, k);
      if (v === undefined) {
        return;
      }
      let n = asFloat(path + `.` + k, v);
      if (n.TAG !== "Ok") {
        err.contents = n._0;
        return;
      }
      out[k] = n._0;
    });
    let e = err.contents;
    if (e !== undefined) {
      return {
        TAG: "Error",
        _0: e
      };
    } else {
      return {
        TAG: "Ok",
        _0: out
      };
    }
  });
}

function decodeRecommendation(path, json) {
  return Belt_Result.flatMap(asObject(path, json), obj => {
    let entityId = decodeStringField(obj, path, "entityId");
    let action = decodeStringField(obj, path, "action");
    let reason = decodeStringField(obj, path, "reason");
    let priority = Belt_Result.flatMap(decodeField(obj, "priority"), v => decodePriority(path + `.priority`, v));
    let confidence = decodeFloatField(obj, path, "confidence");
    let v = decodeOptField(obj, "expectedImprovement");
    let expectedImprovement = v !== undefined ? decodeExpectedImprovement(path + `.expectedImprovement`, v) : ({
        TAG: "Ok",
        _0: {}
      });
    if (entityId.TAG === "Ok") {
      if (action.TAG === "Ok") {
        if (reason.TAG === "Ok") {
          if (priority.TAG === "Ok") {
            if (confidence.TAG === "Ok") {
              if (expectedImprovement.TAG === "Ok") {
                return {
                  TAG: "Ok",
                  _0: {
                    entityId: entityId._0,
                    action: action._0,
                    reason: reason._0,
                    priority: priority._0,
                    confidence: confidence._0,
                    expectedImprovement: expectedImprovement._0
                  }
                };
              } else {
                return {
                  TAG: "Error",
                  _0: expectedImprovement._0
                };
              }
            } else {
              return {
                TAG: "Error",
                _0: confidence._0
              };
            }
          } else {
            return {
              TAG: "Error",
              _0: priority._0
            };
          }
        } else {
          return {
            TAG: "Error",
            _0: reason._0
          };
        }
      } else {
        return {
          TAG: "Error",
          _0: action._0
        };
      }
    } else {
      return {
        TAG: "Error",
        _0: entityId._0
      };
    }
  });
}

function decodeAnalysisResult(json) {
  return Belt_Result.flatMap(asObject("$", json), obj => {
    let eco = Belt_Result.flatMap(decodeField(obj, "eco"), v => decodeEcoMetrics("$.eco", v));
    let econ = Belt_Result.flatMap(decodeField(obj, "econ"), v => decodeEconMetrics("$.econ", v));
    let quality = Belt_Result.flatMap(decodeField(obj, "quality"), v => decodeQualityMetrics("$.quality", v));
    let health = Belt_Result.flatMap(decodeField(obj, "health"), v => decodeHealthIndex("$.health", v));
    let v = decodeOptField(obj, "violations");
    let violations = v !== undefined ? Belt_Result.flatMap(asArray("$.violations", v), arr => mapArray(arr, decodeViolation, "$.violations")) : ({
        TAG: "Ok",
        _0: []
      });
    let v$1 = decodeOptField(obj, "recommendations");
    let recommendations = v$1 !== undefined ? Belt_Result.flatMap(asArray("$.recommendations", v$1), arr => mapArray(arr, decodeRecommendation, "$.recommendations")) : ({
        TAG: "Ok",
        _0: []
      });
    let timestamp = decodeStringField(obj, "$", "timestamp");
    let v$2 = decodeOptField(obj, "commitSha");
    let commitSha = v$2 !== undefined ? Belt_Result.map(asString("$.commitSha", v$2), s => s) : ({
        TAG: "Ok",
        _0: undefined
      });
    if (eco.TAG === "Ok") {
      if (econ.TAG === "Ok") {
        if (quality.TAG === "Ok") {
          if (health.TAG === "Ok") {
            if (violations.TAG === "Ok") {
              if (recommendations.TAG === "Ok") {
                if (timestamp.TAG === "Ok") {
                  if (commitSha.TAG === "Ok") {
                    return {
                      TAG: "Ok",
                      _0: {
                        eco: eco._0,
                        econ: econ._0,
                        quality: quality._0,
                        health: health._0,
                        violations: violations._0,
                        recommendations: recommendations._0,
                        timestamp: timestamp._0,
                        commitSha: commitSha._0
                      }
                    };
                  } else {
                    return {
                      TAG: "Error",
                      _0: commitSha._0
                    };
                  }
                } else {
                  return {
                    TAG: "Error",
                    _0: timestamp._0
                  };
                }
              } else {
                return {
                  TAG: "Error",
                  _0: recommendations._0
                };
              }
            } else {
              return {
                TAG: "Error",
                _0: violations._0
              };
            }
          } else {
            return {
              TAG: "Error",
              _0: health._0
            };
          }
        } else {
          return {
            TAG: "Error",
            _0: quality._0
          };
        }
      } else {
        return {
          TAG: "Error",
          _0: econ._0
        };
      }
    } else {
      return {
        TAG: "Error",
        _0: eco._0
      };
    }
  });
}

async function analyzeRepository(endpoint, repoUrl, ref) {
  let body = Js_dict.fromArray([
    [
      "url",
      repoUrl
    ],
    [
      "ref",
      ref
    ]
  ]);
  try {
    let response = await fetch(endpoint + `/repository`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(body)
    });
    if (response.ok) {
      return decodeAnalysisResult(await response.json());
    } else {
      return {
        TAG: "Error",
        _0: `Analysis failed: ` + response.statusText
      };
    }
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === Stdlib_Exn.$$Error) {
      return {
        TAG: "Error",
        _0: `Analysis request failed: ` + Belt_Option.getWithDefault(e._1.message, "unknown")
      };
    }
    throw e;
  }
}

async function analyzeDiff(endpoint, repoUrl, base, head) {
  let body = Js_dict.fromArray([
    [
      "url",
      repoUrl
    ],
    [
      "base",
      base
    ],
    [
      "head",
      head
    ]
  ]);
  try {
    let response = await fetch(endpoint + `/diff`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(body)
    });
    if (response.ok) {
      return decodeAnalysisResult(await response.json());
    } else {
      return {
        TAG: "Error",
        _0: `Diff analysis failed: ` + response.statusText
      };
    }
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === Stdlib_Exn.$$Error) {
      return {
        TAG: "Error",
        _0: `Analysis request failed: ` + Belt_Option.getWithDefault(e._1.message, "unknown")
      };
    }
    throw e;
  }
}

function mockAnalysis() {
  return {
    eco: {
      carbonScore: 72.0,
      energyScore: 68.0,
      resourceScore: 75.0,
      score: 71.5
    },
    econ: {
      paretoDistance: 0.15,
      allocationScore: 80.0,
      debtScore: 65.0,
      score: 72.0,
      paretoStatus: {
        isOptimal: false,
        distance: 0.15,
        improvements: [
          "Reduce complexity in src/utils.rs",
          "Add memoization to hot path"
        ]
      }
    },
    quality: {
      complexityScore: 70.0,
      couplingScore: 75.0,
      coverageScore: 82.0,
      score: 75.5
    },
    health: {
      eco: 0.4,
      econ: 0.3,
      quality: 0.3,
      total: 72.8,
      grade: "C"
    },
    violations: [],
    recommendations: [{
        entityId: "src/processing.rs",
        action: "optimize_loop",
        reason: "Hot loop could benefit from vectorization",
        priority: "PriorityMedium",
        confidence: 0.78,
        expectedImprovement: Js_dict.fromArray([
          [
            "carbonScore",
            5.0
          ],
          [
            "energyScore",
            8.0
          ]
        ])
      }],
    timestamp: "2024-12-08T10:00:00Z",
    commitSha: "abc123"
  };
}

export {
  decodeField,
  decodeOptField,
  asObject,
  asString,
  asFloat,
  asInt,
  asBool,
  asArray,
  mapArray,
  decodeFloatField,
  decodeStringField,
  decodeBoolField,
  decodeEcoMetrics,
  decodeImprovements,
  decodeParetoStatus,
  decodeEconMetrics,
  decodeQualityMetrics,
  decodeHealthIndex,
  decodeSeverity,
  decodePriority,
  decodeLocation,
  decodeViolation,
  decodeExpectedImprovement,
  decodeRecommendation,
  decodeAnalysisResult,
  analyzeRepository,
  analyzeDiff,
  mockAnalysis,
}
/* No side effect */
