// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

async function analyzeRepository(endpoint, repoUrl, ref) {
  var body = Js_dict.fromArray([
        [
          "url",
          repoUrl
        ],
        [
          "ref",
          ref
        ]
      ]);
  try {
    var response = await fetch(endpoint + "/repository", {
          method: "POST",
          headers: {
            "Content-Type": "application/json"
          },
          body: JSON.stringify(body)
        });
    if (!response.ok) {
      return {
              TAG: "Error",
              _0: "Analysis failed: " + response.statusText
            };
    }
    var json = await response.json();
    return {
            TAG: "Ok",
            _0: json
          };
  }
  catch (raw_e){
    var e = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: "Analysis request failed: " + Belt_Option.getWithDefault(e._1.message, "unknown")
            };
    }
    throw e;
  }
}

async function analyzeDiff(endpoint, repoUrl, base, head) {
  var body = Js_dict.fromArray([
        [
          "url",
          repoUrl
        ],
        [
          "base",
          base
        ],
        [
          "head",
          head
        ]
      ]);
  try {
    var response = await fetch(endpoint + "/diff", {
          method: "POST",
          headers: {
            "Content-Type": "application/json"
          },
          body: JSON.stringify(body)
        });
    if (!response.ok) {
      return {
              TAG: "Error",
              _0: "Diff analysis failed: " + response.statusText
            };
    }
    var json = await response.json();
    return {
            TAG: "Ok",
            _0: json
          };
  }
  catch (raw_e){
    var e = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: "Analysis request failed: " + Belt_Option.getWithDefault(e._1.message, "unknown")
            };
    }
    throw e;
  }
}

function mockAnalysis() {
  return {
          eco: {
            carbonScore: 72.0,
            energyScore: 68.0,
            resourceScore: 75.0,
            score: 71.5
          },
          econ: {
            paretoDistance: 0.15,
            allocationScore: 80.0,
            debtScore: 65.0,
            score: 72.0,
            paretoStatus: {
              isOptimal: false,
              distance: 0.15,
              improvements: [
                "Reduce complexity in src/utils.rs",
                "Add memoization to hot path"
              ]
            }
          },
          quality: {
            complexityScore: 70.0,
            couplingScore: 75.0,
            coverageScore: 82.0,
            score: 75.5
          },
          health: {
            eco: 0.4,
            econ: 0.3,
            quality: 0.3,
            total: 72.8,
            grade: "C"
          },
          violations: [],
          recommendations: [{
              entityId: "src/processing.rs",
              action: "optimize_loop",
              reason: "Hot loop could benefit from vectorization",
              priority: "PriorityMedium",
              confidence: 0.78,
              expectedImprovement: Js_dict.fromArray([
                    [
                      "carbonScore",
                      5.0
                    ],
                    [
                      "energyScore",
                      8.0
                    ]
                  ])
            }],
          timestamp: "2024-12-08T10:00:00Z",
          commitSha: "abc123"
        };
}

export {
  analyzeRepository ,
  analyzeDiff ,
  mockAnalysis ,
}
/* No side effect */
