// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Int from "@rescript/runtime/lib/es6/Belt_Int.js";

function getEnv(key, $$default) {
  let v = Deno.env.get(key);
  if (v !== undefined) {
    return v;
  } else {
    return $$default;
  }
}

function getEnvRequired(key) {
  let v = Deno.env.get(key);
  if (v !== undefined) {
    return {
      TAG: "Ok",
      _0: v
    };
  } else {
    return {
      TAG: "Error",
      _0: `Missing required environment variable: ` + key
    };
  }
}

function getEnvInt(key, $$default) {
  let v = Deno.env.get(key);
  if (v === undefined) {
    return $$default;
  }
  let i = Belt_Int.fromString(v);
  if (i !== undefined) {
    return i;
  } else {
    return $$default;
  }
}

function parseMode(s) {
  let match = s.toLowerCase();
  switch (match) {
    case "consultant" :
      return "Consultant";
    case "regulator" :
      return "Regulator";
    default:
      return "Advisor";
  }
}

function loadPrivateKey() {
  Deno.env.get("GITHUB_PRIVATE_KEY_FILE");
  return getEnv("GITHUB_PRIVATE_KEY", undefined);
}

function allowUnverifiedWebhooks() {
  let v = getEnv("OIKOS_ALLOW_UNVERIFIED_WEBHOOKS", undefined);
  if (v !== undefined) {
    if (v.toLowerCase() === "true") {
      return true;
    } else {
      return v === "1";
    }
  } else {
    return false;
  }
}

function load() {
  let m = getEnv("BOT_MODE", undefined);
  let modeStr = m !== undefined ? m : "advisor";
  let mode = parseMode(modeStr);
  let e = getEnv("ANALYSIS_ENDPOINT", undefined);
  let analysisEndpoint = e !== undefined ? e : "http://localhost:8080/analyze";
  let githubWebhookSecret = getEnv("GITHUB_WEBHOOK_SECRET", undefined);
  let gitlabWebhookSecret = getEnv("GITLAB_WEBHOOK_SECRET", undefined);
  let unverifiedOk = allowUnverifiedWebhooks();
  if (githubWebhookSecret === undefined && gitlabWebhookSecret === undefined && !unverifiedOk) {
    return {
      TAG: "Error",
      _0: "Refusing to start: no webhook secret configured. Set GITHUB_WEBHOOK_SECRET and/or GITLAB_WEBHOOK_SECRET, or pass OIKOS_ALLOW_UNVERIFIED_WEBHOOKS=true for local dev only."
    };
  } else {
    return {
      TAG: "Ok",
      _0: {
        port: getEnvInt("PORT", 3000),
        mode: mode,
        analysisEndpoint: analysisEndpoint,
        githubWebhookSecret: githubWebhookSecret,
        gitlabWebhookSecret: gitlabWebhookSecret,
        githubAppId: getEnv("GITHUB_APP_ID", undefined),
        githubPrivateKey: loadPrivateKey()
      }
    };
  }
}

function modeToString(mode) {
  switch (mode) {
    case "Consultant" :
      return "consultant";
    case "Advisor" :
      return "advisor";
    case "Regulator" :
      return "regulator";
  }
}

export {
  getEnv,
  getEnvRequired,
  getEnvInt,
  parseMode,
  loadPrivateKey,
  allowUnverifiedWebhooks,
  load,
  modeToString,
}
/* No side effect */
