// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Int from "rescript/lib/es6/belt_Int.js";

function getEnv(key, $$default) {
  var v = Deno.env.get(key);
  if (v !== undefined) {
    return v;
  } else {
    return $$default;
  }
}

function getEnvRequired(key) {
  var v = Deno.env.get(key);
  if (v !== undefined) {
    return {
            TAG: "Ok",
            _0: v
          };
  } else {
    return {
            TAG: "Error",
            _0: "Missing required environment variable: " + key
          };
  }
}

function getEnvInt(key, $$default) {
  var v = Deno.env.get(key);
  if (v === undefined) {
    return $$default;
  }
  var i = Belt_Int.fromString(v);
  if (i !== undefined) {
    return i;
  } else {
    return $$default;
  }
}

function parseMode(s) {
  var match = s.toLowerCase();
  switch (match) {
    case "consultant" :
        return "Consultant";
    case "regulator" :
        return "Regulator";
    default:
      return "Advisor";
  }
}

function loadPrivateKey() {
  Deno.env.get("GITHUB_PRIVATE_KEY_FILE");
  return getEnv("GITHUB_PRIVATE_KEY", undefined);
}

function load() {
  var m = getEnv("BOT_MODE", undefined);
  var modeStr = m !== undefined ? m : "advisor";
  var mode = parseMode(modeStr);
  var e = getEnv("ANALYSIS_ENDPOINT", undefined);
  var analysisEndpoint = e !== undefined ? e : "http://localhost:8080/analyze";
  return {
          TAG: "Ok",
          _0: {
            port: getEnvInt("PORT", 3000),
            mode: mode,
            analysisEndpoint: analysisEndpoint,
            githubWebhookSecret: getEnv("GITHUB_WEBHOOK_SECRET", undefined),
            gitlabWebhookSecret: getEnv("GITLAB_WEBHOOK_SECRET", undefined),
            githubAppId: getEnv("GITHUB_APP_ID", undefined),
            githubPrivateKey: loadPrivateKey()
          }
        };
}

function modeToString(mode) {
  switch (mode) {
    case "Consultant" :
        return "consultant";
    case "Advisor" :
        return "advisor";
    case "Regulator" :
        return "regulator";
    
  }
}

export {
  getEnv ,
  getEnvRequired ,
  getEnvInt ,
  parseMode ,
  loadPrivateKey ,
  load ,
  modeToString ,
}
/* No side effect */
