// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Config from "./Config.res.js";
import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_string from "@rescript/runtime/lib/es6/Js_string.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

function getGrade(score) {
  if (score >= 90.0) {
    return "A";
  } else if (score >= 80.0) {
    return "B";
  } else if (score >= 70.0) {
    return "C";
  } else if (score >= 60.0) {
    return "D";
  } else {
    return "F";
  }
}

function getGradeEmoji(grade) {
  switch (grade) {
    case "A" :
      return "🏆";
    case "B" :
      return "✨";
    case "C" :
      return "👍";
    case "D" :
      return "⚠️";
    default:
      return "🚨";
  }
}

function getStatusEmoji(score) {
  if (score >= 70.0) {
    return "✅";
  } else if (score >= 50.0) {
    return "⚠️";
  } else {
    return "❌";
  }
}

function severityToString(s) {
  switch (s) {
    case "Blocking" :
      return "blocking";
    case "High" :
      return "high";
    case "Medium" :
      return "medium";
    case "Low" :
      return "low";
    case "Info" :
      return "info";
  }
}

function generatePRComment(analysis, mode) {
  let grade = getGrade(analysis.health.total);
  let gradeEmoji = getGradeEmoji(grade);
  let healthLine = `### Overall Health: ` + gradeEmoji + ` ` + grade + ` (` + String(analysis.health.total) + `/100)\n\n`;
  let scoreTable = `| Metric | Score | Status |\n|--------|-------|--------|\n` + (`| 🌍 Ecological | ` + String(analysis.eco.score) + ` | ` + getStatusEmoji(analysis.eco.score) + ` |\n`) + (`| 📊 Economic | ` + String(analysis.econ.score) + ` | ` + getStatusEmoji(analysis.econ.score) + ` |\n`) + (`| ⚙️ Quality | ` + String(analysis.quality.score) + ` | ` + getStatusEmoji(analysis.quality.score) + ` |\n\n`);
  let violationsSection;
  if (analysis.violations.length !== 0) {
    let violationLines = Belt_Array.joinWith(Belt_Array.map(analysis.violations, v => {
      let icon = v.severity === "Blocking" ? "🚫" : "⚠️";
      return icon + ` **` + v.policy + `**: ` + v.message + `\n`;
    }), "", s => s);
    violationsSection = `### ⚠️ Policy Violations\n\n` + violationLines + `\n`;
  } else {
    violationsSection = "";
  }
  let recommendationsSection;
  if (analysis.recommendations.length !== 0 && mode !== "Regulator") {
    let maxRecs = mode === "Consultant" ? 10 : 5;
    let topRecs = Belt_Array.slice(analysis.recommendations, 0, maxRecs);
    let recLines = Belt_Array.joinWith(Belt_Array.map(topRecs, r => {
      let confidence = r.confidence * 100.0 | 0;
      return `- **` + r.action + `** (` + String(confidence) + `% confidence): ` + r.reason + `\n`;
    }), "", s => s);
    recommendationsSection = `### 💡 Recommendations\n\n` + recLines + `\n`;
  } else {
    recommendationsSection = "";
  }
  let ps = analysis.econ.paretoStatus;
  let paretoSection;
  if (ps !== undefined) {
    let status;
    if (ps.isOptimal) {
      status = `✅ This code is on the Pareto frontier - no dominated trade-offs detected.\n\n`;
    } else {
      let imps = ps.improvements;
      let improvements = imps !== undefined ? Belt_Array.joinWith(Belt_Array.map(imps, i => `- ` + i + `\n`), "", s => s) : "";
      status = `📍 Distance from Pareto frontier: ` + String(ps.distance) + `\n\n` + (
        improvements !== "" ? `Potential Pareto improvements:\n` + improvements + `\n` : ""
      );
    }
    paretoSection = `### 📈 Pareto Analysis\n\n` + status;
  } else {
    paretoSection = "";
  }
  let footer = `---\n*Analyzed by [Oikos Bot](https://github.com/hyperpolymath/oikos-bot) | ` + (`Mode: ` + Config.modeToString(mode) + ` | `) + `[Learn more about eco-friendly coding](https://greensoftware.foundation/)*\n`;
  return `## 🏛️ Oikos Analysis\n\n` + healthLine + scoreTable + violationsSection + recommendationsSection + paretoSection + footer;
}

function generateDegradedComment(reason, mode) {
  let body = `The analyser could not be reached for this PR, so no eco/econ/quality scores were produced.\n\n` + (`> Reason: ` + reason + `\n\n`);
  let modeNote;
  switch (mode) {
    case "Consultant" :
    case "Advisor" :
      modeNote = `Re-run the bot once the analyser is healthy to get a real report.\n\n`;
      break;
    case "Regulator" :
      modeNote = `**Regulator mode**: this PR will not be auto-approved by Oikos until analysis completes successfully. The maintainer should re-run the bot or merge manually with explicit acknowledgement.\n\n`;
      break;
  }
  let footer = `---\n` + (`*[Oikos Bot](https://github.com/hyperpolymath/oikos) | Mode: ` + Config.modeToString(mode) + ` | Status: degraded*\n`);
  return `## 🏛️ Oikos Analysis — unavailable\n\n` + body + modeNote + footer;
}

function generateSARIF(analysis) {
  let rules = [
    Js_dict.fromArray([
      [
        "id",
        "eco/eco-minimum"
      ],
      [
        "name",
        "EcoMinimum"
      ],
      [
        "shortDescription",
        Js_dict.fromArray([[
            "text",
            "Eco minimum threshold not met"
          ]])
      ]
    ]),
    Js_dict.fromArray([
      [
        "id",
        "eco/eco-standard"
      ],
      [
        "name",
        "EcoStandard"
      ],
      [
        "shortDescription",
        Js_dict.fromArray([[
            "text",
            "Eco standard threshold not met"
          ]])
      ]
    ])
  ];
  let results = Belt_Array.map(analysis.violations, v => Js_dict.fromArray([
    [
      "ruleId",
      `eco/` + Js_string.replace("_", "-", v.policy)
    ],
    [
      "level",
      v.severity === "Blocking" ? "error" : "warning"
    ],
    [
      "message",
      Js_dict.fromArray([[
          "text",
          v.message
        ]])
    ]
  ]));
  return Js_dict.fromArray([
    [
      "$schema",
      "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json"
    ],
    [
      "version",
      "2.1.0"
    ],
    [
      "runs",
      [Js_dict.fromArray([
          [
            "tool",
            Js_dict.fromArray([[
                "driver",
                Js_dict.fromArray([
                  [
                    "name",
                    "oikos-bot"
                  ],
                  [
                    "version",
                    "0.1.0-beta"
                  ],
                  [
                    "informationUri",
                    "https://github.com/hyperpolymath/oikos-bot"
                  ],
                  [
                    "rules",
                    Belt_Array.map(rules, prim => prim)
                  ]
                ])
              ]])
          ],
          [
            "results",
            Belt_Array.map(results, prim => prim)
          ]
        ])]
    ]
  ]);
}

export {
  getGrade,
  getGradeEmoji,
  getStatusEmoji,
  severityToString,
  generatePRComment,
  generateDegradedComment,
  generateSARIF,
}
/* No side effect */
