// Generated by ReScript, PLEASE EDIT WITH CARE


function make() {
  return {
          routes: [],
          middlewares: [],
          notFoundHandler: undefined
        };
}

function methodToString(method) {
  switch (method) {
    case "GET" :
        return "GET";
    case "POST" :
        return "POST";
    case "PUT" :
        return "PUT";
    case "DELETE" :
        return "DELETE";
    case "PATCH" :
        return "PATCH";
    case "OPTIONS" :
        return "OPTIONS";
    case "HEAD" :
        return "HEAD";
    
  }
}

function methodFromString(str) {
  switch (str) {
    case "DELETE" :
        return "DELETE";
    case "GET" :
        return "GET";
    case "HEAD" :
        return "HEAD";
    case "OPTIONS" :
        return "OPTIONS";
    case "PATCH" :
        return "PATCH";
    case "POST" :
        return "POST";
    case "PUT" :
        return "PUT";
    default:
      return ;
  }
}

function matchPath(pattern, path) {
  var patternParts = pattern.split("/").filter(function (p) {
        return p !== "";
      });
  var pathParts = path.split("/").filter(function (p) {
        return p !== "";
      });
  if (patternParts.length !== pathParts.length) {
    return ;
  }
  var params = {};
  var matches = {
    contents: true
  };
  patternParts.forEach(function (patternPart, i) {
        var pathPart = pathParts[i];
        if (!patternPart.startsWith(":")) {
          if (patternPart !== pathPart) {
            matches.contents = false;
            return ;
          } else {
            return ;
          }
        }
        var paramName = patternPart.slice(1);
        params[paramName] = pathPart;
      });
  if (matches.contents) {
    return params;
  }
  
}

function addRoute(router, method, path, handler) {
  var newRoute = {
    method: method,
    path: path,
    handler: handler
  };
  return {
          routes: router.routes.concat([newRoute]),
          middlewares: router.middlewares,
          notFoundHandler: router.notFoundHandler
        };
}

function get(router, path, handler) {
  return addRoute(router, "GET", path, handler);
}

function post(router, path, handler) {
  return addRoute(router, "POST", path, handler);
}

function put(router, path, handler) {
  return addRoute(router, "PUT", path, handler);
}

function $$delete(router, path, handler) {
  return addRoute(router, "DELETE", path, handler);
}

function patch(router, path, handler) {
  return addRoute(router, "PATCH", path, handler);
}

function options(router, path, handler) {
  return addRoute(router, "OPTIONS", path, handler);
}

function use(router, middleware) {
  return {
          routes: router.routes,
          middlewares: router.middlewares.concat([middleware]),
          notFoundHandler: router.notFoundHandler
        };
}

function notFound(router, handler) {
  return {
          routes: router.routes,
          middlewares: router.middlewares,
          notFoundHandler: handler
        };
}

var Url = {};

async function handle(router, req) {
  var methodStr = req.method;
  var url = req.url;
  var urlObj = new URL(url);
  var path = urlObj.pathname;
  var methodEnum = methodFromString(methodStr);
  if (methodEnum === undefined) {
    return new (globalThis.Response)("Method not allowed", {
                status: 405
              });
  }
  var matchingRoute = {
    contents: undefined
  };
  router.routes.forEach(function (route) {
        if (route.method !== methodEnum) {
          return ;
        }
        var _params = matchPath(route.path, path);
        if (_params !== undefined) {
          matchingRoute.contents = route;
          return ;
        }
        
      });
  var route = matchingRoute.contents;
  if (route !== undefined) {
    var finalHandler = function () {
      return route.handler(req);
    };
    var wrappedHandler = router.middlewares.reduceRight((function (next, middleware) {
            return function () {
              return middleware(req, next);
            };
          }), finalHandler);
    return await wrappedHandler();
  }
  var handler = router.notFoundHandler;
  if (handler !== undefined) {
    return await handler(req);
  } else {
    return new (globalThis.Response)("Not Found", {
                status: 404
              });
  }
}

function serve(router, port) {
  return Deno.serve({
              port: port
            }, (async function (req) {
                return await handle(router, req);
              }));
}

export {
  make ,
  methodToString ,
  methodFromString ,
  matchPath ,
  addRoute ,
  get ,
  post ,
  put ,
  $$delete ,
  patch ,
  options ,
  use ,
  notFound ,
  Url ,
  handle ,
  serve ,
}
/* No side effect */
