// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Js_string from "rescript/lib/es6/js_string.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

async function verifyGitHubSignature(payload, signature, secret) {
  var encoder = new (globalThis.TextEncoder)();
  var keyData = encoder.encode(secret);
  var data = encoder.encode(payload);
  var key = await globalThis.crypto.subtle.importKey("raw", keyData, {
        name: "HMAC",
        hash: "SHA-256"
      }, false, [
        "sign",
        "verify"
      ]);
  var signatureBytes = encoder.encode(Js_string.replace("sha256=", "", signature));
  return await globalThis.crypto.subtle.verify("HMAC", key, signatureBytes, data);
}

function verifyGitLabToken(token, secret) {
  return token === secret;
}

function parseGitHubEvent(headers, payload) {
  var eventType = Js_dict.get(headers, "x-github-event");
  var obj = Js_json.decodeObject(payload);
  var action;
  if (obj !== undefined) {
    var a = Js_dict.get(obj, "action");
    action = a !== undefined ? Js_json.decodeString(a) : undefined;
  } else {
    action = undefined;
  }
  if (eventType === undefined) {
    return ;
  }
  var obj$1 = Js_json.decodeObject(payload);
  var repo;
  if (obj$1 !== undefined) {
    var r = Js_dict.get(obj$1, "repository");
    if (r !== undefined) {
      var repoObj = Js_json.decodeObject(r);
      if (repoObj !== undefined) {
        var o = Js_dict.get(repoObj, "owner");
        var owner;
        if (o !== undefined) {
          var ownerObj = Js_json.decodeObject(o);
          if (ownerObj !== undefined) {
            var l = Js_dict.get(ownerObj, "login");
            owner = l !== undefined ? Belt_Option.getWithDefault(Js_json.decodeString(l), "") : "";
          } else {
            owner = "";
          }
        } else {
          owner = "";
        }
        var n = Js_dict.get(repoObj, "name");
        var name = n !== undefined ? Belt_Option.getWithDefault(Js_json.decodeString(n), "") : "";
        var u = Js_dict.get(repoObj, "html_url");
        var url = u !== undefined ? Belt_Option.getWithDefault(Js_json.decodeString(u), "") : "";
        repo = {
          owner: owner,
          name: name,
          url: url
        };
      } else {
        repo = undefined;
      }
    } else {
      repo = undefined;
    }
  } else {
    repo = undefined;
  }
  if (repo !== undefined) {
    return {
            platform: "GitHub",
            eventType: eventType,
            action: action,
            repository: repo,
            payload: payload
          };
  }
  
}

function parseGitLabEvent(headers, payload) {
  var eventType = Js_dict.get(headers, "x-gitlab-event");
  if (eventType === undefined) {
    return ;
  }
  var obj = Js_json.decodeObject(payload);
  var repo;
  if (obj !== undefined) {
    var p = Js_dict.get(obj, "project");
    if (p !== undefined) {
      var projObj = Js_json.decodeObject(p);
      if (projObj !== undefined) {
        var n = Js_dict.get(projObj, "namespace");
        var namespace = n !== undefined ? Belt_Option.getWithDefault(Js_json.decodeString(n), "") : "";
        var n$1 = Js_dict.get(projObj, "name");
        var name = n$1 !== undefined ? Belt_Option.getWithDefault(Js_json.decodeString(n$1), "") : "";
        var u = Js_dict.get(projObj, "web_url");
        var url = u !== undefined ? Belt_Option.getWithDefault(Js_json.decodeString(u), "") : "";
        repo = {
          owner: namespace,
          name: name,
          url: url
        };
      } else {
        repo = undefined;
      }
    } else {
      repo = undefined;
    }
  } else {
    repo = undefined;
  }
  if (repo !== undefined) {
    return {
            platform: "GitLab",
            eventType: eventType,
            action: undefined,
            repository: repo,
            payload: payload
          };
  }
  
}

export {
  verifyGitHubSignature ,
  verifyGitLabToken ,
  parseGitHubEvent ,
  parseGitLabEvent ,
}
/* No side effect */
